### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by geoffreylitt** [somaticio/tensorflow.rb#53]
It looks like this project doesn't have an explicit license noted yet. I know it's still early, but I think it's important to have a license so that potential users and contributors can be assured about the legal status of this code.

I don't know enough about the background of where this project came from to suggest which license might be appropriate, but [this website](http://choosealicense.com/) is fairly informative.

**Comment by jtoy** [comment]
we will be using a BSD3 license

**Comment by geoffreylitt** [comment]
Thanks for adding this to the repo @jtoy!
