### ISSUE TITLE
Add support for Multi Dimensional Tensors for String Data type in tensor

### ISSUE THREAD

**Issue by Arafatk** [somaticio/tensorflow.rb#56]
A good solution to this problem was released in #26. But somehow it's a hack:
- It's actually assuming that there are strings in the tensor.
- It currently can't deal with multi dimensional string arrays.
- Encoding issues of strings are not covered.
  Its best, if we were to have a complete solution for this.

**Comment by chrhansen** [comment]
@Arafatk what is the task specifically for this issue – what is the missing support for string data type?

**Comment by Arafatk** [comment]
@chrhansen The issue here is that we can not use [multidimensional arrays](https://github.com/somaticio/tensorflow.rb/blob/master/lib/tensorflow/tensor.rb#L49) of string data type in tensorflow.rb.

**Comment by jc07** [comment]
@Arafatk I have been looking at the latest developments and its really interesting.     
I think the new API does not support multi-dimensional string tensors.      
I am exploring the API and I want to try this issue.

**Comment by Arafatk** [comment]
@jc07 Thanks a lot for your interest.     
I am glad you are interested in solving the issue, feel free to raise any questions you have regarding this. 
Thanks
