### ISSUE TITLE
Support for Tensorflow r0.12

### ISSUE THREAD

**Issue by ytorii** [somaticio/tensorflow.rb#79]
Recently I found this cool project and installed tensorflow.rb with building `libtensorflow.so` from latest Tensorflow source, but spec test failed with initializing `Session` object. 
This seems mainly because the C API has been changed as below from Tensorflow r0.12 :

- TF_SessionWithGraph has been renamed to TF_Session
- TF_Session has been renamed to TF_DeprecatedSession
 
So do you have any schedules for supporting r0.12 or should I building `libtensorflow.so` from previous versions of Tensorflow?

**Comment by Arafatk** [comment]
@ytorii Yes. I am working on this currently. Many changes were made to the tensorflow C API after the completion of Tensorflow.rb so the tests fail now. 

I will have to completely restructure the gem and it will take some time. But it will be faster and will have a lot more features.

**Comment by ytorii** [comment]
Thank you for your quick response and I'm looking forward to supporting r0.12. If there is be able to help you, please let us  know.

**Comment by Arafatk** [comment]
@ytorii You can take a look at the new tensorflow API and your comments about anything are very welcome.
