### ISSUE TITLE
No tensorflow.rb gem?

### ISSUE THREAD

**Issue by BackOrder** [somaticio/tensorflow.rb#87]
Is there a **tensorflow.rb** gem available?

Does **tensorflow.rb** work on Windows?

**Comment by Arafatk** [comment]
@BackOrder Yes, tensorflow.rb gem is available but I am afraid the installation is not very direct.        
Currently, tensorflow.rb won't work on Windows.    
As for linux you can follow the[ installation instructions](https://github.com/somaticio/tensorflow.rb) or use the [install script](https://github.com/somaticio/tensorflow.rb/blob/master/tools/install.sh).
