### ISSUE TITLE
All of the Medium.com examples that call run fail with error undefined method 'c'

### ISSUE THREAD

**Issue by AshtonO** [somaticio/tensorflow.rb#91]
**Note:** This is not an issue that will require code changes, however it is extremely confusing that the few examples linked to in the main README do not work anymore.  Are there any up-to-date examples of how to use the run command other than the one in the image classification example?

It appears that the `run` method has been changed since the examples on medium.com were all posted.

Now, anywhere that calls `run` breaks because the examples are passing in a dict of `name => tensor` inputs, and run now calls: `port.c` on each input.

This results in the following error:

```/usr/local/rvm/gems/ruby-2.2.0/gems/tensorflow-0.0.1/lib/tensorflow/session.rb:40:in `block in run': undefined method `c' for "input1":String (NoMethodError)```

**Comment by AshtonO** [comment]
I just realized there are run examples within the spec test files.  

I'll close this issue, but still would recommend some editing of the README file to make note that most of the example code provided will no longer work.

**Comment by Arafatk** [comment]
@AshtonO Sorry for the inconvenience. I believe you are referring to the examples on medium.com  blog post.      
I will update the blog post soon.     
Thanks

**Comment by AshtonO** [comment]
Hey Arafat,

Thanks for the response!

Also, I'm wondering if you still work on TensorFlow.rb? I believe I found a
memory leak and am wondering what the best way to discuss this with you is
(assuming you're even working on the project still)

Thanks,
Ashton

On Jun 26, 2017 4:39 PM, "Arafat" <notifications@github.com> wrote:

@AshtonO <https://github.com/ashtono> Sorry for the inconvenience. I
believe you are referring to the examples on medium.com blog post.
I will update the blog post soon.
Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/somaticio/tensorflow.rb/issues/91#issuecomment-311189865>,
or mute the thread

**Comment by Arafatk** [comment]
Hi @AshtonO 
Please email me on arafat.da.khan@gmail.com if you want.    
As for whether I am working on the project or not, I am really busy these days due to a research internship and I am kind of hopping between many things.      
I can still try to make some time if possible over the weekends.
