### ISSUE TITLE
RubyML

### ISSUE THREAD

**Issue by arbox** [somaticio/tensorflow.rb#95]
Dear @Arafatk ,

we've recently added `tensorflow`  to our RubyML list: https://github.com/arbox/machine-learning-with-ruby

In order to connect all Ruby & ML related projects we introduced the `rubyml` topic on GitHub.

Please cosider adding the `rubyml` topic to this repository as well so that the Ruby community can discover this project faster :smiley: 

Thank you in advance!

**Comment by Arafatk** [comment]
Thanks a lot.
Will do it soon.
