### ISSUE TITLE
Could we use pre-compiled `libtensorflow.so` provided by Tensorflow official?

### ISSUE THREAD

**Issue by CicholGricenchos** [somaticio/tensorflow.rb#99]
https://www.tensorflow.org/install/install_c

Tensorflow is providing a script to download `libtensorflow.so` for different platforms. I have tried this and it seems to work well, with all tests passing.

Perhaps we could just use this distributed one and skip the bazel building step.

And moreover, the `libtensorflow.so` and `tensorflow.rb` could be published to Rubygems, then other users just need one gem install command to get started.

**Comment by Arafatk** [comment]
@CicholGricenchos Thanks for the query.     
I did try using precomplied binaries but always had some issues with them so maybe doing the standard way seems okay.      
If it works out for you please let me know.      
Thanks
